<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // Heads-up: assumes you already have leagues, league_participants, league_weeks tables.
        Schema::create('league_week_scores', function (Blueprint $table) {
            $table->id();
            $table->foreignId('league_id')->constrained()->cascadeOnDelete();
            $table->foreignId('league_week_id')->constrained()->cascadeOnDelete(); // generated by LeagueScheduler
            $table->foreignId('league_participant_id')->constrained()->cascadeOnDelete();

            // Scoring config snapshot (copied from league/week at scoring start time)
            $table->unsignedTinyInteger('arrows_per_end')->default(3);
            $table->unsignedTinyInteger('ends_planned')->default(10);
            $table->unsignedTinyInteger('max_score')->default(10); // per arrow max ring (usually 10)
            $table->unsignedTinyInteger('x_value')->default(10);   // X counts as 10 or 11 depending on league

            // Totals (denormalized for quick display)
            $table->unsignedInteger('total_score')->default(0);
            $table->unsignedInteger('x_count')->default(0);

            $table->timestamps();
            $table->unique(['league_week_id', 'league_participant_id'], 'uniq_week_participant');
        });

        Schema::create('league_week_ends', function (Blueprint $table) {
            $table->id();
            $table->foreignId('league_week_score_id')->constrained()->cascadeOnDelete();
            $table->unsignedSmallInteger('end_number'); // 1..N
            $table->json('scores')->nullable();         // [int|null, ...]
            $table->unsignedInteger('end_score')->default(0);
            $table->unsignedInteger('x_count')->default(0);
            $table->timestamps();

            $table->unique(['league_week_score_id', 'end_number']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('league_week_ends');
        Schema::dropIfExists('league_week_scores');
    }
};
